# Numpy Assignments

In [1]:
# Libraries
import numpy as np

In [2]:
def inspect(x):
    print(f'Shape : {x.shape}\nDimensions : {x.ndim}\nSize: {x.size}\nContent : \n{x}')

### 1) Create a 1D array of numbers from 0 to 9.



In [3]:
x = np.arange(0, 10)
inspect(x)

Shape : (10,)
Dimensions : 1
Size: 10
Content : 
[0 1 2 3 4 5 6 7 8 9]


### 2) Create a 3×3 numpy array of all True’s

In [4]:
x = np.ones((3, 3), dtype = bool)
inspect(x)

Shape : (3, 3)
Dimensions : 2
Size: 9
Content : 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 3) Given an array as input, print only odd numbers as output

In [5]:
x = np.arange(0, 20)
inspect(x)
y = x[np.where(x%2)]
print('\n')
inspect(y)

Shape : (20,)
Dimensions : 1
Size: 20
Content : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Shape : (10,)
Dimensions : 1
Size: 10
Content : 
[ 1  3  5  7  9 11 13 15 17 19]


### 4) Replace all odd numbers in arr with -2

In [6]:
x = np.arange(0, 20)
x[np.where(x%2)] = -2
inspect(x)

Shape : (20,)
Dimensions : 1
Size: 20
Content : 
[ 0 -2  2 -2  4 -2  6 -2  8 -2 10 -2 12 -2 14 -2 16 -2 18 -2]


### 5) How to reshape an array?

In [7]:
x = np.arange(0, 20)
inspect(x)
y = x.reshape((10, 2))
# y = np.reshape(x, (10, 2))
print('\n')
inspect(y)

Shape : (20,)
Dimensions : 1
Size: 20
Content : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Shape : (10, 2)
Dimensions : 2
Size: 20
Content : 
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


### 6) Convert a 1D array to a 2D array with 2 rows

In [8]:
x = np.arange(0, 20)
inspect(x)
y = x.reshape((2, int(x.size/2)))
# y = np.reshape(x, (10, 2))
# inspect(np.reshape(data, (2, -1)))
print('\n')
inspect(y)


Shape : (20,)
Dimensions : 1
Size: 20
Content : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Shape : (2, 10)
Dimensions : 2
Size: 20
Content : 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


### 7) Given an array  a  = \[1,2,3,4,5,6,7,8,9\] , create  new array b from a such that b includes all odd numbers and 4 multiples. 

In [9]:
data = np.arange(1, 10)
x = data[np.where(np.logical_or(
    data % 2 != 0, 
    data % 4 == 0
))]
print(x)

[1 3 4 5 7 8 9]


### 8) Given array, check if there are any null values and print them out. 

In [10]:
x = np.arange(0, 20)
inspect(np.isnan(x))

Shape : (20,)
Dimensions : 1
Size: 20
Content : 
[False False False False False False False False False False False False
 False False False False False False False False]


### 9) How to replace all missing values with 0 in a numpy array?

In [11]:
x = np.arange(0, 20, dtype = float)
x[10] = np.nan
x[11] = np.nan
x[12] = np.nan
inspect(x)
x[np.where(np.isnan(x))] = 0
print('\n')
inspect(x)

Shape : (20,)
Dimensions : 1
Size: 20
Content : 
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. nan nan nan 13. 14. 15. 16. 17.
 18. 19.]


Shape : (20,)
Dimensions : 1
Size: 20
Content : 
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.  0.  0.  0. 13. 14. 15. 16. 17.
 18. 19.]


### 10) How to find the count of each unique number in a NumPy array?

In [12]:
x = np.array([1, 2, 3, 4, 5, 6, 1, 3, 4, 1, 3, 5, 4])
unique, counts = np.unique(x, return_counts = True)

inspect(np.asarray((unique, counts)).T)

Shape : (6, 2)
Dimensions : 2
Size: 12
Content : 
[[1 3]
 [2 1]
 [3 3]
 [4 3]
 [5 2]
 [6 1]]


### 11) How to convert a numeric to a categorical (text) array?

In [13]:
x = np.array([10, 20, 30, 40, 50])
x = x.astype('<U1')
x

array(['1', '2', '3', '4', '5'], dtype='<U1')

### 12) Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both.

In [14]:
x = np.arange(99, 300)
x[np.where(
    np.logical_and(
        np.logical_or(
            (
                x % 5 == 0
            ), 
            (
                x % 7 == 0
            )
        ), 
        np.logical_not(
            np.logical_and(
                (
                    x % 5 == 0
                ), 
                (
                    x % 7 == 0
                )
            )
        )
    )
)]

array([100, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 145, 147,
       150, 154, 155, 160, 161, 165, 168, 170, 180, 182, 185, 189, 190,
       195, 196, 200, 203, 205, 215, 217, 220, 224, 225, 230, 231, 235,
       238, 240, 250, 252, 255, 259, 260, 265, 266, 270, 273, 275, 285,
       287, 290, 294, 295])

### 13) Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [15]:
x = np.array([10, 20, 30, 40, 50])
y = x[-1::-1]
inspect(y)

Shape : (5,)
Dimensions : 1
Size: 5
Content : 
[50 40 30 20 10]
